### ISSUE TITLE
Add installation instructions?

### ISSUE THREAD

**Issue by ChillarAnand** [vkazanov/elpygen#1]

**Comment by vkazanov** [comment]
Done. The package is not on Melpa yet, so you should go for manual installation.

One question though: how did you find out about the package? I only finished it this morning :-)

**Comment by gopar** [comment]
Looks like this can be closed? 😉 

Also, looks like I this better than [pygen](https://github.com/JackCrawley/pygen/) Less keybindings. \o/

**Comment by ChillarAnand** [comment]
> One question though: how did you find out about the package? I only finished it this morning :-)

Through elpy.

**Comment by vkazanov** [comment]
@gopar Well... pygen has two deficiencies: it uses external python-mode.el, which makes it unusable with Elpy, and, yes, it has by far too many keybindings. 

Elpygen right now does not have all the features (implement classes, static methods, variables, etc). My plan is to have less features, but try as hard as possible to make all of them available in a dwim-like manner, i.e. through a single keybinding.

Besides, I do not intend to switch Pycharm any time soon ;-) The IDE gets a few things right, but many more - wrong.
